//! Wire protocol types for hsm-rs (gRPC + JSON sidecar).
//!
//! Generated by `tonic-build` from `proto/hsm_v1.proto`. Downstream
//! callers import from `hsm_proto::v1`:
//!
//! - `data_mover_client::DataMoverClient` — plugin side.
//! - `data_mover_server::{DataMover, DataMoverServer}` — daemon side.
//! - `hsm_control_server::{HsmControl, HsmControlServer}` — hsmctl server.
//! - `hsm_control_client::HsmControlClient` — hsmctl client.
//! - Message types: `Hello`, `Welcome`, `ActionItem`, `ActionStatus`,
//!   `BackendObject`, `FromPlugin`, `ToPlugin`, plus the oneof inner
//!   enums `from_plugin::Body`, `to_plugin::Body`.
//! - Management messages: `CtlStatusRequest/Response`, `CtlAgentInfo`,
//!   `CtlListAgentsRequest/Response`, `CtlListActionsRequest/Response`,
//!   `CtlActionRecord`.

#![allow(missing_docs)] // generated code

/// hsm.v1 — daemon ↔ local plugin (gRPC over UDS).
pub mod v1 {
    tonic::include_proto!("hsm.v1");
}

#[cfg(test)]
mod tests {
    use super::v1::{
        ActionItem, ActionKind, FromPlugin, Hello, ToPlugin, Welcome, from_plugin, to_plugin,
    };

    #[test]
    fn handshake_envelope_round_trips() {
        let hello = FromPlugin {
            body: Some(from_plugin::Body::Hello(Hello {
                agent_id: "noop-0".into(),
                archive_ids: vec![1, 2],
                version: "0.0.1".into(),
            })),
        };
        // Verify the oneof body can be matched out cleanly.
        match hello.body.unwrap() {
            from_plugin::Body::Hello(h) => {
                assert_eq!(h.agent_id, "noop-0");
                assert_eq!(h.archive_ids, vec![1, 2]);
            }
            other => panic!("expected Hello, got {other:?}"),
        }
    }

    #[test]
    fn welcome_envelope_round_trips() {
        let welcome = ToPlugin {
            body: Some(to_plugin::Body::Welcome(Welcome {
                session_id: "s-1".into(),
            })),
        };
        match welcome.body.unwrap() {
            to_plugin::Body::Welcome(w) => assert_eq!(w.session_id, "s-1"),
            other => panic!("expected Welcome, got {other:?}"),
        }
    }

    #[test]
    fn action_item_default_kind_is_unspecified() {
        let a = ActionItem::default();
        assert_eq!(a.kind, ActionKind::Unspecified as i32);
    }

    #[test]
    fn action_kind_round_trips_via_i32() {
        for k in [
            ActionKind::Archive,
            ActionKind::Restore,
            ActionKind::Remove,
            ActionKind::Cancel,
        ] {
            assert_eq!(ActionKind::try_from(k as i32).unwrap(), k);
        }
    }
}
