//! Wire protocol types for hsm-rs.
//!
//! Generated by `tonic-build` from `proto/hsm_v1.proto`. The generated module
//! is included as `v1`; downstream code uses
//! `hsm_proto::v1::data_mover_client::DataMoverClient` / `…server::DataMoverServer`.

#![allow(missing_docs)] // generated code

/// hsm.v1 — daemon ↔ local plugin (gRPC over UDS).
pub mod v1 {
    tonic::include_proto!("hsm.v1");
}

#[cfg(test)]
mod tests {
    use super::v1::{ActionItem, ActionKind, BackendObject};

    #[test]
    fn action_kind_default_is_unspecified() {
        let a = ActionItem::default();
        // Generated enums have an UNSPECIFIED zero value (proto3 default).
        assert_eq!(a.kind, ActionKind::Unspecified as i32);
    }

    #[test]
    fn backend_object_default_constructible() {
        // Just exercise the generated struct + serde derives compile.
        let b = BackendObject::default();
        assert!(b.uuid.is_empty());
        assert!(b.hash.is_empty());
        assert!(b.url.is_empty());
    }

    #[test]
    fn action_kind_round_trips_via_i32() {
        // Conversion path daemon will use: enum → i32 → enum.
        for k in [
            ActionKind::Archive,
            ActionKind::Restore,
            ActionKind::Remove,
            ActionKind::Cancel,
        ] {
            let n = k as i32;
            let back = ActionKind::try_from(n).unwrap();
            assert_eq!(back, k);
        }
    }
}
